# Generated by Django 3.0.8 on 2020-11-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('advanced', models.BooleanField(default=False)),
                ('followers', models.IntegerField(default=0)),
                ('forks', models.IntegerField(default=0)),
                ('stars', models.IntegerField(default=0)),
                ('repositories', models.IntegerField(default=0)),
                ('created', models.CharField(default='2008-04-10', max_length=10)),
                ('updated', models.CharField(default='2008-04-10', max_length=10)),
            ],
        ),
    ]
