# Generated by Django 3.0.8 on 2020-10-07 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitrequest',
            name='num_items',
        ),
    ]
